check_process
sub_scripts/testing_process.sh

Adapt sample to latest Yunohost example: is_public is now a boolean.
As many packages still use a string format, leave the previous is_public specification as a comment.

Adapt script to allow the use of numbers for is_public value

---

README.md

README needs to be updated with  the new default public/private boolean definition.

Make README consistent with check_process

---

sub_scripts/testing_process.sh

Currently, when an app fails the `public` or `private` test, only a "Test failed!" message is displayed. The root cause of the failure is missing – which leaves us wondering whether something went wrong during the installation itself, or what exactly happened during the privacy check.
This PR adds a warning about the cause of the failure, which should make these tests easier to understand and to fix.

testing_process: better explain why public/private test fails

---

sub_scripts/lxc_check.sh

Fix the lxc_check bridge check always failing : checking for the bridge should grep `addr` (instead of `adr`).

lxc_check: fix bridge check

---

sub_scripts/launcher.sh

When attempting to create snap2, if snap1 doesn't exist, `lxc-snapshot` will create a snapshot named `snap1` (instead of `snap2`). In this case we need to rename snap1 into snap2.
However the condition check is wrong: after creating the snapshot, snap1 will *always* exist – even if it didn't before. Thus the renaming never happens.
Fix the issue by detecting the absence of snap2 (rather than snap1).

launcher: fix creation of snap2

---

sub_scripts/lxc_build.sh

lxc_build.sh requires some packages that are not automatically installed if APT is configured to ignore recommends dependencies (i.e. *APT::Install-Recommends "true";*). 
I know that such APT configuration is unusual but maybe it can prevent others to get stuck.

Explicitely install some required packages.

---

sub_scripts/launcher.sh
sub_scripts/lxc_build.sh
sub_scripts/lxc_check.sh

lxc-create doesn't take in count aarch64 : https://uk.images.linuxcontainers.org/
But aarch64=arm64, so the changes do the trick to let install package_check on aarch64
In addition, when container start on aarch64, the container need more time to initialize network part, nslookup only respond after a few seconds. Adding some time after lxc start allow ping -q -c 2 security.debian.org or ping -q -c 2 yunohost.org to work

Add support for aarch64

---

package_check.sh
sub_scripts/testing_process.sh

**Not tested** :/ 
That's a follow-up of https://github.com/YunoHost/package_linter/pull/77 to handle a new special return code (2) meaning the app should be considered as broken / level 0

Handle return code from linter saying the app should be flagged as broken

---

sub_scripts/launcher.sh

When we remove patch in a new package version it's not removed in the test. In case of test of an upgrade could have some old patch which is applied but it should because it was removed.
Use rsync wich give the possiblity to remove old file.
Tested locally. And it work.

Use rsync to push package and delete old files

---

sub_scripts/testing_process.sh

People are repeatedly confused by these checks which ain't accurate/relevant in many situation (e.g. script is legitimately small and therefore there isn't much comment etc...) yet because the messages are in screaming red people think there's a huge error going on ...
So proposing to disable this until these checks are made more accurate...

Disable check_template

---

sub_scripts/lxc_build.sh

Hopefully that's the reason why so many tests randomly fails because dpkg/apt lock is unavailable

Disable apt-daily to prevent it from messing with dpkg/apt locks

---

package_check.sh

In an attempt to reduce the time it takes to run package_check, it should be noticed that incorrect_path is now obsolete since 2.7 yet is still ran for many apps. The only reason it could still be relevant is for a handful of apps that use `path=$2` for example (instead of `$YNH_APP_...`). This is now also fixed in 3.8 so this test is obsolete.
Note that the test port_already_used also seems overkilled for apps that do not ask a port argument from the manifest. (Typically it's only about making sure that apps obtain a port using `ynh_find_port` which can easily be checked from the package linter)

Test incorrect_path is obsolete and should be removed

---

levels.list
package_check.sh

Not the most revolutionary change ever, but while starting to work on something else in package_check, I remember about this level list that's sitting in https://github.com/YunoHost/apps/tree/master/app_levels and this list (and translation) is actually not used anywhere else besides package_check ... so this is an attempt to simplify / clean things by moving them in package check directly

Integrate level list directly into package_check

---

package_check.sh

c.f. neutrinet_ynh whose main branch is stable and not master 
https://github.com/YunoHost/apps/blob/master/apps.json#L1994
therefore the CI fails miserably : 
https://ci-apps.yunohost.org/ci/job/2333

Check that master branch does indeed exists or fallback to stable

---

sub_scripts/lxc_build.sh

On my rpi2 (and on the rpi3 of ppr) the script fails miserably when trying to create a debian buster container with this error:
> Création d'une machine debian buster minimaliste.
debootstrap is /usr/sbin/debootstrap
Checking cache download in /var/cache/lxc/debian/rootfs-buster-armhf ... 
gpg: key 7638D0442B90D010: 4 signatures not checked due to missing keys
gpg: key 7638D0442B90D010: "Debian Archive Automatic Signing Key (8/jessie) <ftpmaster@debian.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Downloading debian minimal ...
I: Target architecture can be executed
I: Retrieving InRelease 
I: Checking Release signature
**E: Release signed by unknown key (key id DCC9EFBF77E11517)**
**The specified keyring /var/cache/lxc/debian/archive-key.gpg may be …

Fix the creation of containers on arm boards

---

package_check.sh
sub_scripts/testing_process.sh

N.B. : this is absolutely not tested...
- Level computation was broken in the multi-test-suite case ... c.f. for example the level 6 definition : 
```
[ $RESULT_linter_level_6 -eq 1 ]
```
should be 
```
[ $RESULT_linter_level_6 -eq 1 ] || \
([ $RESULT_linter_level_6 -eq 0 ] && \
[ "${level[6]}" == "2" ] )
```
- Also I got fed up of the mess this part was so I rewrote it to be a bit more readable / elegant though still far from perfect ... Seriously considering rewriting that part in python >_>

Cleanup + fix level computation

---

package_check.sh

When I try to stop the tests, I mash `ctrl + c` until package_check ends (otherwise it will start the following test). But the cleanup function stop running because of that.
I think we can disable ctrl+c signal (SIGINT) during the cleanup function

disable trap SIGINT in cleanup

---

README.md

Upon first `./package_check.sh app_ynh` command, the script complains about `lynx` not being installed. Let's make sure it is installed like the other dependencies.

Add lynx in the apt install command

---

lib/lxc.sh
lib/tests.sh
lib/tests_coordination.sh

Fix: 
> su: invalid option -- 'r'
> Try 'su --help' for more information.
And when an arg is a sentence and not just a word
(for example: https://ci-apps.yunohost.org/ci/job/213, https://github.com/YunoHost-Apps/unattended_upgrades_ynh/blob/4e342d41ea448c4a9de2bbbc6b6cffe92320ef71/check_process#L3)

Fix lxc exec

---

lib/tests.sh

There are packages like https://github.com/YunoHost-Apps/yunorunner_ynh_core that require pre-installed stuff. but when running a test upgrade from previous version, previous version install fails because pre-installed stuff is not installed ....
Just trying to fix that ... Ugly...

preinstall during upgrade

---

README.md

First execution failed due to missing installation of jq
```
$ ./package_check.sh grr_ynh
Critical: Please install jq
```

Add jq in required dependencies

---

lib/lxc.sh

I was struggling on some package_check without understanding the result of the `[Test 2/6] Installation on the root` test:
https://ci-apps-dev.yunohost.org/ci/job/3189
```
Error: Connection error...
Warning: Test URL: sub.domain.tld
Real URL: curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
/bin/bash: line 2: 192.168.47.254: command not found
/bin/bash: line 3: 192.168.47.254: command not found
/bin/bash: line 4: 192.168.47.254: command not found
/bin/bash: line 5: 192.168.47.254: command not found
HTTP code: curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
/bin/bash: line 2: 192.168.47.254: command not found
/bin/bash: line 3: 192.168.47.254: command not found
/bin/bash: line 4: 192.168.47.254: command not …
```

Retrieve only one IP address

---

lib/common.sh

If in the `./config`, `DIST=buster`, you should be able to provide the `DEFAULT_PHP_VERSION`
Another way to do that, would be having an array of `DIST:DEFAULT_PHP_VERSION` and defining `DEFAULT_PHP_VERSION` from the `DIST` provided

Let configure default php version

---

lib/common.sh
lib/tests_coordination.sh

This addition provides metrics measurements for package_check. The idea is to provide app maintainers infos about their apps that they will be able to fill into the manifestv2.
Todo:

Add metrics measurements to tests runs

---

lib/tests.sh

The public information could be in manifest.toml at `install.init_main_permission` or `resources.permissions` or in manifest.json `is_public`.
Why not just check the ssowat conf to determine if the permission is actually public or not?

Check ssowat conf instead of turbo parsing manifest.json or manifest.toml

---

lib/default_install_args.py

For choices, default value is the first of either list or dict.
The current code is buggy because isinstance() requires a variable and a type.

Fix get_default_values

---

lib/common.sh

The current time display is ambiguous:
> Working time for this test: 4 minutes, 16 seconds (02:19:02)
So i changed the `date` command to force the UTC usage (in fact the showed time will remain unchanged, as the server already uses UTC) and to show that we’re using UTC timezone, removing any ambiguity:
> Working time for this test: 4 minutes, 16 seconds (02:19:02 UTC)

Force current hour in UTC and show explicitly that we’re using UTC

---

lib/tests.sh

cURL --location will follow redirects, but by default won't reuse cookies. 
Some apps, like Jackett, might add authentication cookies in a chain of redirections.
Passing --cookie <useless file> to cURL tells it to keep cookies between 'sessions'.

When testing for app page access, reuse cookies between requests.

---

lib/common.sh

This will provide a real RAM metric of the container, and not of the full system.
For disk usage that won't change anything.

Run resource metrics inside container.

---

.gitignore

I'm not sure if package_linter should be in the gitignore but since it's not in the repo as a submodule i assume yes?

Add more entries to the .gitignore file

---

lib/lxc.sh

This greatly simplifies the VM starting logic:
- only try to start the VM once... why would it work after a failure when repeating the same steps?
- apply a hard 10s timeout (with SIGKILL) on attempts to check if systemd has booted and the network is available ; this means the initial setup step should at worst fail after ~100s (5x10 + 5x10)
- fail this entire `_LXC_CREATE` initial step and therefore the entire test suite if bringing up the VM failed... as the message used to say, it failed miserably, and so there is no reason to keep going and run into weirder and weirder errors such as the instance name not existing because it was not created
Works for me™

Fail startup/network timeout earlier. Exit whole test suite.

---

README.md

ZFS could be an alternative but it's not provided by most distributions. BTRFS is available in mainline kernel, it's the default for Incus upstream, and provides really good performance for snapshots.
After personal testing the `dir` driver was pathologically slow and it should not be recommended even though it's still LXD's default setting for some reason.

Recommend btrfs storage driver for better perf (default on Incus)

---

lib/curl_tests.py

My [Grist package](https://github.com/YunoHost-Apps/grist_ynh) is marked as broken since package_check has checked the assets.
By taking a closer look, I realized that it wasn't an issue of my package, nor of the upstream app, but of the checker.
Indeed, the browser resolves assets (scripts and stylesheets) paths either from the domain, but also if present using the `<base>` tag ([mdn documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base)).
1. We extract the base domain
2. We use [urljoin](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urljoin) to resolve the asset full url (base can be of the form `https://{domain}/path/to/` or a absolute path without the domain like `/path/to/`).

Extract base tag href for resolving asset URLs

---

lib/curl_tests.py

Reopen #176 with a fix to the issue @alexAubin mentioned here: https://github.com/YunoHost/package_check/pull/176#issuecomment-2429601078

Fix wrong asset 404 error

---

README.md
package_check.sh

Branch, distribution version and arch were still in the help but not parsed by the script

Remove non parsed options

---

lib/curl_tests.py

This fixes handling of pages with links like `https://example.com//asset.css` (see https://ci-apps-dev.yunohost.org/ci/job/4483) and fixes (?) regression from #178 that potentially breaks pages that use `base` tag.
This is done by properly parsing URIs with `urlparse`, replacing host/`netloc` and supplementing `scheme` as necessary.

Use proper URI parsing for asset tests.

---

lib/curl_tests.py

In #185 I broke previous fix for Grist from #176.
That's because Grist uses `<base>` tag and I disregarded it.
Tested with:
- NocoDB (relative path to non-root in subdomain)
- Grist (uses `<base href="/some/location/">` tag)
-  Piped (uses `<base href="/">`)
- Element (a standard app on subpath that uses relative linking)

Fixed Grist again as it uses non-/ `base` tag.

---

package_check.sh

Just specify the `-b` option once to the git clone command ([it is already passed here](https://github.com/YunoHost/package_check/blob/57bc7703d50d853bd0e3c4805250e30efe837141/lib/common.sh#L362)).

Fix usage of `-b`

---

lib/parse_tests_toml.py

I get this warning:
```
[REDACTED]/./lib/parse_tests_toml.py:167: SyntaxWarning: invalid escape sequence '\|'
f"grep -q '^ynh_add_nginx_config\|^ynh_nginx_add_config\|^ynh_config_add_nginx' '{str(basedir)}/scripts/install'"
Traceback (most recent call last):
```
We escape the antislashes, as it is specified in a command wrapped in double-quote

Fix is_webapp grep pattern

---

lib/tests.sh
lib/tests_coordination.sh

postinstall scripts may require long time and can be subject to errors. Indeed, in many case, they are run to add domains and install app dependencies.
They were run several times often right after restauring the initial snapshot.
That's the reason why in this commit we snapshot right after running preinstall and we take advantage of it.

Snapshot after running postinstall

---

lib/tests_coordination.sh

This notably fix the following error in the CI:
```
Validating that the app docs can/can't be accessed with its URL...
Traceback (most recent call last):
File "<string>", line 1, in <module>
import toml, sys; t = toml.loads(sys.stdin.read()); print(toml.dumps(t[''].get('curl_tests', {})))
```
This is because abeb76b4f55ec82db08263cb525251242702d437 overwrites the global `current_test_serie` variable. We rather create here another local variable.

Fix wrong assignment leading to error

---

lib/tests.sh

1. Don't use sed to pass variables, but rather pass them to the script. This fixes issues where variables were called with other syntaxes like `${MY_VAR}` instead of just `$MY_VAR`
2. Use `-x` option to trace what is being called. This is particularly useful when debugging and see what failed in these scripts. Also the output is more eloquent when the commands in the pre scripts produce logs themselves.
3. Use options to stop the script at the first error, which is the default behavior when packaging.
The last point is the most arguable I would say, especially as it might be a breaking change in some cases, I won't mind to remove it.

Improve pre* scripts invocation

---

lib/curl_tests.py

Tested with success against nextcloud (which is AFAIK the package which makes the most advanced use of curl tests)

curl_tests: Force interface incusbr0 to be used

---

lib/curl_tests.py

When creating custom domains in the tests, the curl tests don't recognize them as being part of the incus container and does not request it.
Use wildcard to redirect all the domains to the incus container. Quoting [this documentation](https://curl.se/libcurl/c/CURLOPT_RESOLVE.html):
> Specify the host as a single asterisk (*) to match all names. This wildcard is resolved last so any resolve with a specific host and port number is given priority.

curl_tests: Redirect any request to the incus container
