YunoHost/package_check

README.md, check_process, package_check.sh, sub_scripts/testing_process.sh
https://github.com/YunoHost/doc/pull/432
=> Ajout des niveaux

package_check.sh
Should reduce spam detection, but not even sure.
=> [enh] Change sender enveloppe

README-fr.md, README.md
=> Document to explain in a ticket why a level have been forced

README-fr.md, README.md, check_process, package_check.sh, sub_scripts/lxc_force_start.sh, sub_scripts/testing_process.sh
=> Pre install

README-fr.md, README.md, check_process, package_check.sh
Related to https://github.com/YunoHost/apps/pull/677
**This PR should be merged after https://github.com/YunoHost/apps/pull/678**
=> Modify levels 4, 6 and 8

package_check.sh
I've used this example:
https://unix.stackexchange.com/a/180678
=> Fix sed level 8

sub_scripts/testing_process.sh
This package `php7.*-uploadprogress` create files: /etc/php/{5.6,7.0,7.1,7.2,7.3,7.4}/mods-available/uploadprogress.ini
Check the folder `/etc/php/7.0/fpm` instead of `/etc/php/7.0`
=> check fpm folder

README-fr.md, README.md, check_process, package_check.sh, sub_scripts/log_extractor.sh, sub_scripts/testing_process.sh
Tested with my_webapp with new tests for actions and config_panel.
And currently testing with leed without any change into the check_process.
=> Add new tests for actions and config_panel

sub_scripts/testing_process.sh
in backup script there is now 4 `ynh_print_info`
=> add specific count of progression indicator for backup

sub_scripts/lxc_build.sh
`aa_profile` is now `apparmor.profile` on buster
=> fix apparmor on buster

levels.list, package_check.sh, sub_scripts/lxc_build.sh, sub_scripts/testing_process.sh
Follow-up of https://github.com/YunoHost/package_linter/pull/87 and discussions at last meeting.
This is an untested draft of implementation, not sure what I'm doing .. I'm suspecting there are some edge cases when there are multiple test suites but I don't really understand that mechanism :/
=> Implement new definitions for level 7, 8, 9

README.md, build_base_lxc.sh, lib/common.sh
Tested on my side, and half working because `slapd.service` failed at the end of the YunoHost install and the postinstall was failed
=> Add cross arch support

lib/tests.sh, lib/tests_coordination.sh
We don't want to test a change url to an untested path
=> fix change_url tests

sub_scripts/testing_process.sh
To be merged after version 4.1
=> add --force during the upgrade test

lib/tests.sh
=> revert on false typo

lib/analyze_test_results.py, lib/common.sh
Yolocommited, to be actually tested on the battlefield ...
The point is that in addition to the badge that yunorunner posts under the "!testme" stuff, we should also display the test results right below to avoid clicking and scrolling logs to check what level the test yields + possible warnings
=> yolo: Export test summary as image

README.md, lib/tests.sh, lib/tests_coordination.sh
As a packager, I would like to be able to set up instructions before upgrading. Therefore I could add some data to the app and ensure the migration succeeds.
I propose to add a `;; pre-upgrade` section which would act like `;; pre-install`, but would be also given a `$FROM_COMMIT` variable so the packager can handle the particularities of each version before upgrading.
Example given in the `README.md`:
```
; pre-upgrade
set -euxo pipefail
if [ "$FROM_COMMIT" == '65c382d138596fcb32b4c97c39398815a1dcd4e8' ]
then
resolve=127.0.0.1:443:$DOMAIN
curl -X POST --data '{"some-key": "some-value"}' https://$DOMAIN/$PATH --resolve "$resolve"
fi
```
Example using [meilisearch_ynh](https://github.com/YunoHost-Apps/meilisearch_ynh):
```
; pre-upgrade
set -euxo pipefail
if [ "$FROM_COMMIT" == …
```
=> Pre upgrade scripts

lib/tests_coordination.sh
Fix #124 
My fix is quite ugly but tested and working
=> Make all tests

lib/tests_coordination.sh, package_check.sh
- :tada: New `package_check.sh -e` parameter! *Pauses the tests on errors*
- Fix #118
=> enh: Pause on errors

lib/common.sh, lib/lxc.sh, lib/tests_coordination.sh
This is a small readability fix.
=> Use text instead of integers for stop_timer argument

lib/common.sh, lib/lxc.sh, lib/tests.sh, lib/tests_coordination.sh
Mostly various fixes, though related to https://github.com/YunoHost/yunorunner/pull/48
=> Moar refactoring

lib/tests.sh
An original idea from @Salamandar :p
=> Don't remove the app when install fails

lib/tests_coordination.sh
yolocommit
I need to run this at least once before we merge this /o\
=> Publish logs with YunoPaste on failure

lib/build_base_lxc.sh, lib/common.sh, lib/lxc.sh, lib/tests.sh, lib/tests_coordination.sh, package_check.sh
In the future, we could remove LXD support, making the README way shorter (no snap, etc)
=> Allow the use of incus instead of LXD.

lib/common.sh
Some apps don't have a master or stable branch, but a main branch.
=> support main branch for app to test as git repository

package_check.sh
To prevent creating huge files in the system partition or ramfs /tmp
=> Add --storage-dir argument

README.md, lib/curl_tests.py, lib/tests.sh
cf example in the README or in https://github.com/YunoHost-Apps/nextcloud_ynh/pull/719
=> Add ability to define "curl tests" in tests.toml

README.md
Also add a warning about conflict with Docker.
=> Improve the README setup to mention incus

lib/lxc.sh
Broke the CI, tired of debugging other people stuff
=> Revert "Fail startup/network timeout earlier. Exit whole test suite."

.github/workflows/shellcheck.yml, lib/build_base_lxc.sh, lib/common.sh, lib/lxc.sh, lib/stupid_autorepair_because_lxd_is_a_fucking_idiot.sh, lib/tests.sh, lib/tests_coordination.sh, lib/witness.sh, package_check.sh
There might be some impacting changes, let's test it before merging it and breaking our CI again™
=> Fix all shellcheck issues

.gitignore, requirements.txt
- Added `requirements.txt`
- Added `.venv` to gitignore
All that for people who want to tinker with Python part of the process.
=> requirements.txt + gitignore
